# Generated by Django 4.1.7 on 2023-09-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_cv_birth_place_cv_dob_cv_email_cv_f_name_cv_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CV',
            new_name='Cartoon',
        ),
        migrations.RenameModel(
            old_name='Forms',
            new_name='Play',
        ),
    ]
